### ISSUE TITLE
Is there a 2015 date set yet?

### ISSUE THREAD

**Issue by BrianGenisio** [nodebots/nodebotsday#137]
EOM

**Comment by dshaw** [comment]
7/27 is the default date.

**Comment by dshaw** [comment]
Ouch, that's a Monday. Probably not a great day. What do folks think? Saturday, July 25th?

**Comment by nodebotanist** [comment]
+1 for Saturday the 25th. Trying to Saturday OR Sunday last year was confusing.

**Comment by lynnaloo** [comment]
Saturday the 25th works well for Norfolk.

**Comment by dshaw** [comment]
Yes, feedback across the board has been KIS and on one date. Thank you. Keep the feedback coming.

**+1 for Saturday, July 25th 2015.**

**Comment by BrianGenisio** [comment]
Awesome.  Adding it to my calendar.  Looking to create an Ann Arbor, Michigan event.  :+1:

**Comment by dshaw** [comment]
Great. Thanks, @BrianGenisio. Looking forward to having you on board. I'm going to keep this issue open a bit longer to make sure we get feedback from more international locations.

**Comment by BrianGenisio** [comment]
:+1:

**Comment by jurasec** [comment]
Saturday, July 25th 2015 is pretty well for [México] (http://www.meetup.com/NodeBotsMX/)

**Comment by avermeulen** [comment]
+1 for Cape Town

**Comment by ykro** [comment]
25th works for Guatemala :)

**Comment by garrows** [comment]
Should be good for Australia.

**Comment by nexxy** [comment]
25th = Saturday = AWESOME!

so much more room for activities.

https://www.youtube.com/watch?v=29jij4ldkNs

**Comment by gorhgorh** [comment]
it works for paris too

**Comment by BrianGenisio** [comment]
This list is making me happy. :smiley_cat:

**Comment by robtarr** [comment]
We would like to organize an event in Dayton, OH for this date as well.

**Comment by onel0p3z** [comment]
Please add :palm_tree:  Miami, FL :palm_tree: to the list. Looking forward to it <3

**Comment by mcwhittemore** [comment]
+1 to the 25th
/cc @cshenoy

**Comment by BrianGenisio** [comment]
Any chance we can open up a Gitter.im channel for this repo to discuss?  We're in the brainstorming phase for planning our Ann Arbor event.  It would be awesome to have a place to bounce ideas around with other organizers! :)

**Comment by ykro** [comment]
That would be awesome :) or we could use slack ... I'd would really like to
spend this nodebots day in a different country and want to help as much as
I can to my co-organizers previous to the event so the local community can have
a blast like last year :)

On Thursday, February 5, 2015, Brian Genisio <notifications@github.com>
wrote:

> Any chance we can open up a Gitter.im channel for this repo to discuss?
> We're in the brainstorming phase for planning our Ann Arbor event. It would
> be awesome to have a place to bounce ideas around with other organizers! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/nodebotsday/issues/137#issuecomment-73156794>
> .
>


-- 
Saludos,

  --Adrian

**Comment by robtarr** [comment]
I would love a Slack channel, but anything would be great!

**Comment by dshaw** [comment]
Great, I created https://nodebotsday.slack.com for us to kick off 2015 prep. I invited everyone here except @onel0p3z and @gorhgorh who I didn't have email for.

I'll be tied up until the end of next week with Node Summit. After that, we should all hop on a Hangout together.

**Comment by makenai** [comment]
Vegas is in for Sat 25 also.

**Comment by dshaw** [comment]
@makenai Invited you to Slack

**Comment by TheAlphaNerd** [comment]
i'd love to get in on the slack

**Comment by gorhgorh** [comment]
@dshaw gorhgorh at lesnodebots.eu

**Comment by onel0p3z** [comment]
@dshaw onel0p3z [at] gmail [dot] com ;) Thank you !!

**Comment by dshaw** [comment]
@TheAlphaNerd @gorhgorh @onel0p3z Invites sent.

@makenai is working to setup an easier onboarding process similar to what VegasJS and Socket.io do. Stay tuned.

**Comment by makenai** [comment]
You can get yourself an invite here:

https://nodebotsday-chat.herokuapp.com/

Enjoy!

**Comment by lynnaloo** [comment]
Nice work @makenai

**Comment by makenai** [comment]
UPDATE: Slack changed their API 5 days ago, so the above link no longer works: https://github.com/rauchg/slackin/issues/15

Will work on getting it replaced or fixed soon. You can shoot me a gmail (same as my username here) for an invite until then.

**Comment by dshaw** [comment]
Thanks, @makenai
