### ISSUE TITLE
2015 NodeBots Day planning

### ISSUE THREAD

**Issue by dshaw** [nodebots/nodebotsday#139]
Let's kick off NodeBots Day planning. We have a ton of interest, let's connect the resources to the groups all across the world.

I'd like to build out working groups similar to what io.js has been doing, but first I think we should build out a "core team". Please raise your hand if you are interested and have time to contribute and help others have a great NodeBots Day 2015.

**Comment by bryan-m-hughes** [comment]
✋ I'm in

**Comment by RussTheAerialist** [comment]
Please count me in

**Comment by AnnaGerber** [comment]
I'm in

**Comment by olizilla** [comment]
:+1:

**Comment by gorhgorh** [comment]
I'm in

2015-02-19 0:19 GMT+01:00 Oli Evans <notifications@github.com>:

**Comment by gorhgorh** [comment]
count me in

**Comment by blujconcepts** [comment]
I'm building a NodeBots Dallas and would love to join the core team :)

**Comment by Kryz** [comment]
I'm in (NodeBots Montevideo).

**Comment by onel0p3z** [comment]
I'm in :point_up:

**Comment by Resseguie** [comment]
:hand:

**Comment by blujconcepts** [comment]
Looking forward to getting started, finally got the ball rolling with creating a Meetup here!!

**Comment by ajfisher** [comment]
We've just started planning for NBD here in Aus as shipping things etc tends to take a bit longer.

**Comment by lynnaloo** [comment]
If there are any organizers that aren't in the NodeBotsDay Slack, let me know!
